### ISSUE TITLE
Using An Unknown Language in Code Blocks Crashes the App

### ISSUE THREAD

**Issue by SE2Dev** [QuebicApp/manifesto#14]
Crash Report:
-----------------------------------------------
Message: Reason: Error: Unknown language: "svelte"
-----------------------------------------------
Source: N/A:0:0
-----------------------------------------------
Stack: at: Error
    at new SZ (https://app.quebic.com/dist/7c85e8a1863085dc111b.js:1:1172161)
    at SZ.then (<anonymous>)
    at Ge (https://app.quebic.com/dist/a3401a88c86bc005e375.js:2:479272)
    at JI (https://app.quebic.com/dist/7c85e8a1863085dc111b.js:1:463165)
    at KI (https://app.quebic.com/dist/7c85e8a1863085dc111b.js:1:463714)
    at it (https://app.quebic.com/dist/a3401a88c86bc005e375.js:2:481847)
    at new tL (https://app.quebic.com/dist/7c85e8a1863085dc111b.js:1:464064)
    at Array.DT (https://app.quebic.com/dist/7c85e8a1863085dc111b.js:1:518945)
    at GT (https://app.quebic.com/dist/7c85e8a1863085dc111b.js:1:520098)
    at it (https://app.quebic.com/dist/a3401a88c86bc005e375.js:2:481847)
-----------------------------------------------

**Comment by dtzxporter** [comment]
Fixed.
